export const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: "90%",
  height: "90%",
  bgcolor: "background.paper",
  borderRadius: "12px",
  border: "none",
  outline: "none",
  boxShadow: 24,
  overflowY: "scroll",
  p: 4,
};
